name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Ganti "main" kalau branch kamu pakai nama lain

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # folder tempat file index.html dan lainnya

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
